### PR TITLE
Add Typescript Typings

### LINKED ISSUE #103: Add type hints.
Add type hints to enable better use of this lib and support with typescript

### PR DESCRIPTION
**Pull request by Darkflame72**
Will fix #103 and will aid in future development.

### CODE REVIEW

**Comment by Darkflame72** [comment]
Currently it is all autogenerated so I will manually add the correct types so it isn't `any` for everything

**Comment by rom1504** [comment]
Is there a way to avoid duplicating the typings for all the versions ? The interface followed should be exactly the same for any version

**Comment by Darkflame72** [comment]
Yeah I should be able to do that. Are there any differences from an interface perspective for the dev using it per version or is it just internal?

**Comment by rom1504** [comment]
No there should be no difference, we are using this without checking the version at all inside mineflayer (see https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/blocks.js ) and inside prismarine-world.
The implementation per version is different due to mojang changing the network format.

That's one of the main point of prismarine-chunk actually, it hides away all the dirty implementation details of the network format behind an unique API.

**Comment by Darkflame72** [comment]
Ok awesome I will have this done today and should be ready for review

**Comment by Darkflame72** [comment]
This should fix that but I will double check everything to make sure and finish up types.

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
