### PR TITLE
PaletteStorage.incrementPalette fix

### PR DESCRIPTION
**Pull request by lowlines**
See https://github.com/PrismarineJS/prismarine-chunk/issues/183

### CODE REVIEW

**Comment by nickelpro** [comment]
This looks like an appropriate fix to me, pinging @extremeheat

Also rom is going to want a test case that fails on the current code so that this doesn't get reintroduced from a future re-factor or something like that.

**Comment by extremeheat** [comment]
OK, will defer to nickelpro, LGTM

Is there a reason to be exposing the internal classes top level? This does not sound right, it's not a documented part of the package

**Comment by lowlines** [comment]
Exposing the internal classes is unrelated to this fix. Feel free to ignore those changes.

**Comment by extremeheat** [comment]
Can you fix? (If not @nickelpro should have write perms to fix)

**Review by extremeheat — APPROVED** [review]

**Comment by nickelpro** [comment]
I only verified the actual fix. My eyes glazed over the exposure/TS stuff 😅

I assume people know what they're doing with typings because I certainly don't

**Comment by extremeheat** [comment]
I'm was thinking we could prevent this by changing for loop condition, but can't think of a fix that way.

LGTM for merge @nickelpro

**Comment by nickelpro** [comment]
LGTM @rom1504

**Comment by nickelpro** [comment]
This still needs a test case ya!

**Comment by rom1504** [comment]
please add a test

**Comment by rom1504** [comment]
conflict, please resolve and re open if you want

**Pull request closed without merging**
