### PR TITLE
implement 1.8 chunk bitmap (/section)

### LINKED ISSUE #8: Implement the 0x21 map_chunk bitmap
Minecraft network packet 0x21 map_chunk allows for a bitmap to specify which 16x16x16 minichunks are included and which are left out to be filled with air. Currently there is no way of using this, and the entirety of the chunk must be sent over the wire.

### PR DESCRIPTION
**Pull request by rom1504**
I believe it works but because of #24 it's not really thoroughly tested.
Fix #8 
Related to #19

### CODE REVIEW

**Comment by rom1504** [comment]
Indeed dump and load are actually mostly untested and don't seem to actually work.

Add some tests.

**Comment by rom1504** [comment]
Ok so I believe it works now.
But I wouldn't say my test are really thorough.
For example I do not test with a bitmap != 0xFFFF

Although I believe it should work, I will test this with mineflayer before merging.

**Comment by rom1504** [comment]
tested with mineflayer

**Comment by rom1504** [comment]
testing with flying-squid before merging

**Comment by polkovnikov-ph** [comment]
Holding fingers crossed for this PR.

**Comment by rom1504** [comment]
okay flying-squid works with this.

**Pull request merged**
