### PR TITLE
Fix setBlock calling setSkylight when chunk does not have skylight

### LINKED ISSUE #186: The value of "offset" is out of range. It must be >= 0 and <= 10239. Received 10684
The bot is crashing when joining the server. I dont have the exact code this is happening with.
However, I do know that this is being caused by a sign in the nether, which when destroyed it the bot wont crash while logging in, when replaced it will crash

stacktrace
https://sourceb.in/1iB0fA68TD

### PR DESCRIPTION
**Pull request by frej4189**
Closes #186

### CODE REVIEW

**Comment by frej4189** [comment]
Appears to break 1.19+ for some odd reason

**Comment by frej4189** [comment]
> Appears to break 1.19+ for some odd reason

Might just be nether being broken in 1.19+ in general (including in current release).

**Comment by extremeheat** [comment]
Possibly, that will need to be fixed

**Comment by extremeheat** [comment]
There should be a test here also

**Pull request merged**
