### PR TITLE
SetBlockData for 1.13

### PR DESCRIPTION
**Pull request by Deudly**

### CODE REVIEW

**Comment by Karang** [comment]
Could you also update :
* https://github.com/PrismarineJS/prismarine-chunk/blob/master/src/pc/1.15/ChunkColumn.js#L124
* https://github.com/PrismarineJS/prismarine-chunk/blob/master/src/pc/1.14/ChunkColumn.js#L126
With the same code ?
It would be one less thing to worry about later.

**Comment by rom1504** [comment]
And the 1.9 one too please

**Comment by Karang** [comment]
> And the 1.9 one too please

it is already implemented https://github.com/PrismarineJS/prismarine-chunk/blob/master/src/pc/1.9/ChunkColumn.js#L101

**Comment by rom1504** [comment]
Ah yeah right it's a bit different so I did that already

**Comment by Deudly** [comment]
Done!

**Pull request merged**
