### PR TITLE
Update 1.18 chunk dump

### PR DESCRIPTION
**Pull request by nickelpro**
Update the chunk dump to include lighting data from the main chunk packet

### CODE REVIEW

**Comment by rom1504** [comment]
988 seems like too many files

**Comment by rom1504** [comment]
988 seems like too many files

**Comment by nickelpro** [comment]
It's adding 200 files and removing the 788 that are there currently, for a total of 988 files changed.

I'm _getting rid of_ 588 files

**Comment by rom1504** [comment]
yeah indeed it was wrong before
it's still wrong after this pr though
the right number is 20 .dump files.
chunk dumper allows you to get exactly 20

**Comment by nickelpro** [comment]
Ah, didn't realize we had a standard. I'll close and re-open with correct data

**Pull request closed without merging**
