### PR TITLE
Block sections are not biomes

### PR DESCRIPTION
**Pull request by nickelpro**
Minor copy-paste bug fix

### CODE REVIEW

**Comment by extremeheat** [comment]
yeah I had a feeling the problem was around here...

**Comment by rom1504** [comment]
How come it doesn't break any test :) ?
Can we easily add a non regression test ?

**Comment by nickelpro** [comment]
I don't even know what this code is used for, I just spotted the error idly browsing diffs.

I'm not sure what to test for exactly, I guess you could write a stupid test that checks these exact variables are set to correct constants but that seems very narrow and fragile. It's not testing a broad function, just that these constants were set correctly

**Comment by rom1504** [comment]
I mean, what is the consequence of having incorrect values for bitsPerValue and maxBits for singleValueContainer?
shouldn't it break something?

**Comment by rom1504** [comment]
Ok

**Pull request merged**
